### ISSUE TITLE
`main` is red: `test_report.py` calls `position_size` without the broker argument #233 made required

### ISSUE THREAD

**Issue by B-Tshehla** [beezhub/fundamental-bias-engine#245]
For the risk desk.

`main` is red at 32103ec. One test fails, and it has been failing since #233
merged.

### Observed behaviour

```
$ python -m pytest -q tests/test_report.py::test_a_zero_balance_cannot_reach_a_renderer
E   TypeError: position_size() missing 1 required positional argument: 'broker'
tests/test_report.py:1802: TypeError
```

Reproduced on a clean checkout of `main` at 32103ec on 2026-09-22, with no
local changes.

### Cause

#233 made `broker` a required parameter of `fbe.risk.position_size`. Its own
tests and `tests/test_position_size.py` were updated. `tests/test_report.py`
calls the same function at line 1802 and was not, so it still calls it with the
old signature.

The test itself is not wrong about anything: it guards that a zero balance
cannot reach a renderer, which is unrelated to broker profiles. It just calls
a function whose signature moved.

### Why this was not caught

The pull request that landed it ran its own files rather than the suite, or ran
the suite and read the wrong exit code. Worth a glance at whichever it was,
because a signature change is exactly the kind that reaches a caller in another
file.

### Acceptance criteria

- [ ] `tests/test_report.py::test_a_zero_balance_cannot_reach_a_renderer` passes
      on `main`, with the call updated to pass a broker profile.
- [ ] The whole suite passes on `main`, verified by the summary line rather than
      by a shell exit code.
- [ ] Every other caller of `position_size` outside `src/` is checked in the
      same pass, so a second one does not turn up tomorrow.

### Affected modules and owner

`tests/test_report.py`. Risk desk, since #233 is theirs.

Found while working #126, whose branch carries the same failure inherited from
`main` and does not cause it.

**Comment by B-Tshehla** [comment]
Closing as a duplicate. Nothing to build.

When I filed this at 2026-09-22, `main` was red because #233 left one call site without the `broker` argument. That was already known as #234, which has since merged. I did not find it before filing, which I should have.

The symptom on `main` has changed since and is worse: the file no longer parses at all, so no test in the repository collects. #234's one-line fix was ported onto three branches while it waited, #237 put the line before `risk_fraction` and #241 put it after, and the two merged without conflicting, so the argument is now passed twice. That is #243, and #244 fixes it.

Verified #244 just now: on its branch `tests/test_report.py` collects and all 108 of its tests pass. It is a one-line deletion.

Nothing here is mine to do. Follow #243 and #244.
